-- =============================================================
-- Projects + add-venture pipeline runs + venture_dossiers thin read-model
-- =============================================================

INSERT INTO migrations (name) VALUES ('006_projects_and_add_venture') ON CONFLICT (name) DO NOTHING;

-- =============================================================
-- SCHEMA: PLATFORM (shared across tenants)
-- =============================================================
CREATE SCHEMA IF NOT EXISTS platform;

-- Projects: one row per .projects/<nickname>/ folder on disk.
-- Nickname is generated by @bruce/project-store (docker-names + 3-char alnum
-- suffix + optional `_N` collision fallback). UNIQUE enforces the folder name
-- can't collide across concurrent scans.
CREATE TABLE IF NOT EXISTS platform.projects (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    account_id TEXT NOT NULL,
    nickname TEXT NOT NULL UNIQUE,
    venture_id UUID,
    title TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_platform_projects_account_id ON platform.projects(account_id);
CREATE INDEX IF NOT EXISTS idx_platform_projects_venture_id ON platform.projects(venture_id);
-- text_pattern_ops enables fast `LIKE '<base>%'` prefix lookups used by
-- `ensureUnique` to find the largest `_N` suffix for a base nickname.
CREATE INDEX IF NOT EXISTS idx_platform_projects_account_nickname_prefix
    ON platform.projects (account_id, nickname text_pattern_ops);

-- =============================================================
-- add_venture.pipeline_runs: flow-only, no full payload
-- =============================================================
CREATE TABLE IF NOT EXISTS add_venture.pipeline_runs (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    account_id UUID NOT NULL,
    venture_id UUID,
    opportunity_id UUID,
    project_nickname TEXT,
    temporal_workflow_id TEXT,
    status TEXT NOT NULL DEFAULT 'pending',
    error_message TEXT,
    started_at TIMESTAMPTZ,
    ended_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_add_venture_pipeline_runs_account_id
    ON add_venture.pipeline_runs(account_id);
CREATE INDEX IF NOT EXISTS idx_add_venture_pipeline_runs_venture_id
    ON add_venture.pipeline_runs(venture_id);
CREATE INDEX IF NOT EXISTS idx_add_venture_pipeline_runs_project_nickname
    ON add_venture.pipeline_runs(project_nickname);
CREATE INDEX IF NOT EXISTS idx_add_venture_pipeline_runs_status
    ON add_venture.pipeline_runs(status);

ALTER TABLE add_venture.pipeline_runs ENABLE ROW LEVEL SECURITY;
CREATE POLICY add_venture_pipeline_runs_policy ON add_venture.pipeline_runs
    USING (check_account_access(account_id));

-- =============================================================
-- Extend add_venture.venture_dossiers with thin read-model columns
-- =============================================================
ALTER TABLE add_venture.venture_dossiers
    ADD COLUMN IF NOT EXISTS pipeline_run_id UUID,
    ADD COLUMN IF NOT EXISTS project_nickname TEXT,
    ADD COLUMN IF NOT EXISTS venture_name TEXT,
    ADD COLUMN IF NOT EXISTS critic_score NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS status TEXT;

CREATE INDEX IF NOT EXISTS idx_venture_dossiers_pipeline_run_id
    ON add_venture.venture_dossiers(pipeline_run_id);
CREATE INDEX IF NOT EXISTS idx_venture_dossiers_project_nickname
    ON add_venture.venture_dossiers(project_nickname);
CREATE INDEX IF NOT EXISTS idx_venture_dossiers_status
    ON add_venture.venture_dossiers(status);
-- Allow upsert by (account_id, pipeline_run_id) — the single source of truth
-- for a dossier read-model row while the full JSON lives on disk.
CREATE UNIQUE INDEX IF NOT EXISTS idx_venture_dossiers_account_pipeline_run
    ON add_venture.venture_dossiers(account_id, pipeline_run_id)
    WHERE pipeline_run_id IS NOT NULL;
