import { index, jsonb, pgSchema, text, timestamp, uniqueIndex, uuid } from 'drizzle-orm/pg-core';

/**
 * Global platform data (not tenant-scoped). OpenRouter catalog is synced from their API.
 */
export const platformSchema = pgSchema('platform');

export const openrouterModels = platformSchema.table(
  'openrouter_models',
  {
    id: text('id').primaryKey(),
    canonical_slug: text('canonical_slug'),
    payload: jsonb('payload').notNull().$type<Record<string, unknown>>(),
    synced_at: timestamp('synced_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    canonicalIdx: index('idx_openrouter_models_canonical_slug').on(table.canonical_slug),
    syncedIdx: index('idx_openrouter_models_synced_at').on(table.synced_at),
  }),
);

/**
 * platform.projects — one row per `.projects/<nickname>/` folder on disk.
 * The `nickname` is generated by `@bruce/project-store` and is globally
 * unique, serving as the filesystem folder name for a project's deliverables.
 */
export const projects = platformSchema.table(
  'projects',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    account_id: text('account_id').notNull(),
    nickname: text('nickname').notNull(),
    venture_id: uuid('venture_id'),
    title: text('title'),
    created_at: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    nicknameUnique: uniqueIndex('platform_projects_nickname_unique').on(table.nickname),
    accountIdx: index('idx_platform_projects_account_id').on(table.account_id),
    ventureIdx: index('idx_platform_projects_venture_id').on(table.venture_id),
  }),
);
